name: Node CI

on: push
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm run build
        npm run test
        npm run generate
      env:
        CI: true
        NO_AUTHOR_CHECK: true

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Trainee Package
        # Directory containing files to upload
        path: dist/trainee.zip

    - name: upload coverage
      uses: codecov/codecov-action@v1
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
